// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrdjIPSIhnQjZuiQ1DsRNFUngs0vXIF_4',
    appId: '1:385003370337:web:44c6fad4e10def2bd47720',
    messagingSenderId: '385003370337',
    projectId: 'e-santren',
    authDomain: 'e-santren.firebaseapp.com',
    storageBucket: 'e-santren.appspot.com',
    measurementId: 'G-3D9PPBNZ6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUzCFpsGhVbAckRPW9lLL4t8KM1hHxUMg',
    appId: '1:385003370337:android:86d4bba9d33e3f47d47720',
    messagingSenderId: '385003370337',
    projectId: 'e-santren',
    storageBucket: 'e-santren.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqIRg1M8mBvtNiqdYMM2J7ye8U8XY5orM',
    appId: '1:385003370337:ios:56b08f78856cf209d47720',
    messagingSenderId: '385003370337',
    projectId: 'e-santren',
    storageBucket: 'e-santren.appspot.com',
    iosClientId: '385003370337-qhrf3s3i8r9ljg6t4oa4od2d09jcmvqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.esantrenInsightsV1',
  );
}
